version: 2.1

jobs:
  build:
    docker:
      - image: node:20-buster
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - ./dist
  build:
    docker:
      - image: node:20-buster
    steps:
      - attach_workspace:
          at: ./
      - run: ls -la
      - run: |
          type -p curl >/dev/null || (apt update && apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && apt update \
          && apt install gh -y
      - run: npm install
      - run: npm run build
workflows:
  build_and_publish:
    jobs:
      - build
