version: 2.1

jobs:
  build:
    docker:
      - image: node:16-buster
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - ./dist
  publish:
    docker:
      - image: node:16-buster
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: cd dist && ls -la
      - run: 
          name: Install Github CLI
          command: |
            type -p curl >/dev/null || (apt update && apt install curl -y)
            curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
            && chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && apt update \
            && apt install gh -y
      - run: 
          name: Install jq
          command: apt install jq -y

      - run: |
          export version=$(cat package.json | jq -r '.version')
          gh release create ${version} ./dist/tailwindcompile-win.exe ./dist/tailwindcompile-linux
      #- run: gh release upload $(cat package.json | jq -r '.version') ./dist/tailwindcompile-win.exe ./dist/tailwindcompile-linux

workflows:
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build
