version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: npm install
      - run: npm run build

workflows:
  build_and_publish:
    jobs:
      - build
