version: 2.1

jobs:
  build:
    docker:
      - image: node:16.20.0-buster-slim
    steps:
      - checkout
      - run: npm install
      - run: npm run build

workflows:
  build_and_publish:
    jobs:
      - build
